VERSION="2.0.0"
ACCOUNTS="GANKOSO5GT6XCWVPTMY5IXV5BF5EJR2SHQLKJ4REUQMJ3MV3CH34LSXP"
SQ02_EASTER_EGG="Log into series 2 of Stellar Quest then visit quest.stellar.org/series2. Finally drag and drop your Stellar Quest series 2 badge PNG images onto the screen. Enjoy!"
